apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-node2
  namespace: argocd
  labels:
    app.kubernetes.io/name: test-node2
spec:
  project: default
  source:
    repoURL: https://github.com/Backstage-GoldenImage/k8s-artifact.git
    targetRevision: main
    path: apps/test-node2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
