apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-test-31
  labels:
    backstage.io/kubernetes-id: demo-test-31
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-test-31
  template:
    metadata:
      labels:
        app: demo-test-31
        backstage.io/kubernetes-id: demo-test-31
    spec:
      containers:
        - name: demo-test-31
          image: ghcr.io/backstagessppoc/demo-test-31:96186a5694734bd7be52ea9f719b9d5b398a74d9
          imagePullPolicy: Always
          ports:
            - containerPort: 3000