apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-test-20
  labels:
    backstage.io/kubernetes-id: demo-test-20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-test-20
  template:
    metadata:
      labels:
        app: demo-test-20
        backstage.io/kubernetes-id: demo-test-20
    spec:
      containers:
        - name: demo-test-20
          image: ghcr.io/backstagessppoc/demo-test-20:255b8d39097f5c4a186898f85de2848a241563f3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000