apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-test6
  labels:
    backstage.io/kubernetes-id: gssp-test6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-test6
  template:
    metadata:
      labels:
        app: gssp-test6
        backstage.io/kubernetes-id: gssp-test6
    spec:
      containers:
        - name: gssp-test6
          image: chaitanyapandeygspann/gssp-test6:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000