apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-test-pr-8
  labels:
    backstage.io/kubernetes-id: gssp-test-pr-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-test-pr-8
  template:
    metadata:
      labels:
        app: gssp-test-pr-8
        backstage.io/kubernetes-id: gssp-test-pr-8
    spec:
      containers:
        - name: gssp-test-pr-8
          image: chaitanyapandeygspann/gssp-test-pr-8:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000