apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-test-27
  labels:
    backstage.io/kubernetes-id: demo-test-27
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-test-27
  template:
    metadata:
      labels:
        app: demo-test-27
        backstage.io/kubernetes-id: demo-test-27
    spec:
      containers:
        - name: demo-test-27
          image: ghcr.io/backstagessppoc/demo-test-27:56f11281477ef22c11e0e19d320eab69b3a5bae5
          imagePullPolicy: Always
          ports:
            - containerPort: 3000