apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-test11
  labels:
    backstage.io/kubernetes-id: gssp-test11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-test11
  template:
    metadata:
      labels:
        app: gssp-test11
        backstage.io/kubernetes-id: gssp-test11
    spec:
      containers:
        - name: gssp-test11
          image: chaitanyapandeygspann/gssp-test11:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000