apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node1
  labels:
    backstage.io/kubernetes-id: test-node1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-node1
  template:
    metadata:
      labels:
        app: test-node1
        backstage.io/kubernetes-id: test-node1
    spec:
      containers:
        - name: test-node1
          image: chaitanyapandeygspann/test-node1:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000