apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gssp-test-a5
  namespace: argocd
  labels:
    app.kubernetes.io/name: gssp-test-a5
spec:
  project: default
  source:
    repoURL: https://github.com/Backstage-GoldenImage/k8s-artifact.git
    targetRevision: main
    path: apps/gssp-test-a5
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true

      selfHeal: true

