apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-test7
  labels:
    backstage.io/kubernetes-id: gssp-test7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-test7
  template:
    metadata:
      labels:
        app: gssp-test7
        backstage.io/kubernetes-id: gssp-test7
    spec:
      containers:
        - name: gssp-test7
          image: chaitanyapandeygspann/gssp-test7:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000