apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  labels:
    backstage.io/kubernetes-id: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
        backstage.io/kubernetes-id: 
    spec:
      containers:
        - name: 
          image: ghcr.io/backstagessppoc/demo-test-18:e5df4a8b2397824bae93d2b4d1c07913f0b88194
          imagePullPolicy: Always
          ports:
            - containerPort: 3000