apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-25-mar-2026-03
  labels:
    backstage.io/kubernetes-id: gssp-25-mar-2026-03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-25-mar-2026-03
  template:
    metadata:
      labels:
        app: gssp-25-mar-2026-03
        backstage.io/kubernetes-id: gssp-25-mar-2026-03
    spec:
      containers:
        - name: gssp-25-mar-2026-03
          image: chaitanyapandeygspann/gssp-25-mar-2026-03:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000