apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-test-26
  labels:
    backstage.io/kubernetes-id: demo-test-26
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-test-26
  template:
    metadata:
      labels:
        app: demo-test-26
        backstage.io/kubernetes-id: demo-test-26
    spec:
      containers:
        - name: demo-test-26
          image: ghcr.io/backstagessppoc/demo-test-26:5857a8b7b4a47893d2cf493c9ea60a535ce2a05e
          imagePullPolicy: Always
          ports:
            - containerPort: 3000