apiVersion: apps/v1
kind: Deployment
metadata:
  name: gssp-test-pr-10
  labels:
    backstage.io/kubernetes-id: gssp-test-pr-10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gssp-test-pr-10
  template:
    metadata:
      labels:
        app: gssp-test-pr-10
        backstage.io/kubernetes-id: gssp-test-pr-10
    spec:
      containers:
        - name: gssp-test-pr-10
          image: chaitanyapandeygspann/gssp-test-pr-10:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000